// Mock data for the LMS system
export const mockUsers = [
  {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    phone: "+1 (555) 123-4567",
    role: "student" as const,
    avatar: "/admin-avatar.png",
    status: "active" as const,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Dr. Sarah Wilson",
    email: "sarah@example.com",
    phone: "+1 (555) 234-5678",
    role: "instructor" as const,
    avatar: "/instructor-avatar-1.jpg",
    bio: "Experienced React developer with 8+ years in frontend development. Passionate about teaching modern web technologies and helping students build real-world applications.",
    expertise: ["React", "JavaScript", "TypeScript", "Node.js", "CSS", "HTML"],
    coursesCount: 12,
    studentsCount: 1250,
    rating: 4.8,
    status: "active" as const,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "3",
    name: "Prof. Michael Chen",
    email: "michael@example.com",
    phone: "+1 (555) 345-6789",
    role: "instructor" as const,
    avatar: "/instructor-avatar-1.jpg",
    bio: "Full-stack developer and educator specializing in backend technologies, database design, and system architecture. PhD in Computer Science.",
    expertise: ["Node.js", "Python", "PostgreSQL", "MongoDB", "Docker", "AWS"],
    coursesCount: 8,
    studentsCount: 890,
    rating: 4.9,
    status: "active" as const,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    id: "4",
    name: "Admin User",
    email: "admin@example.com",
    phone: "+1 (555) 456-7890",
    role: "admin" as const,
    avatar: "/admin-avatar.png",
    status: "active" as const,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "5",
    name: "Emily Johnson",
    email: "emily@example.com",
    phone: "+1 (555) 567-8901",
    role: "student" as const,
    status: "active" as const,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "6",
    name: "David Rodriguez",
    email: "david@example.com",
    phone: "+1 (555) 678-9012",
    role: "instructor" as const,
    bio: "Data scientist and machine learning expert with focus on practical applications and industry best practices.",
    expertise: ["Python", "Machine Learning", "Data Science", "TensorFlow", "Pandas", "NumPy"],
    coursesCount: 5,
    studentsCount: 432,
    rating: 4.7,
    status: "inactive" as const,
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-15"),
  },
]

export const mockCourses = [
  {
    id: "course1",
    title: "Complete React Development",
    description: "Master React from basics to advanced concepts",
    thumbnail: "/react-course-thumbnail.jpg",
    instructorId: "2",
    instructor: mockUsers.find((u) => u.id === "2"),
    status: "published" as const,
    price: 99,
    duration: 40,
    category: "Web Development",
    subcategory: "Frontend",
    subject: "React",
    language: "English",
    level: "Intermediate",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "course2",
    title: "Node.js Backend Mastery",
    description: "Build scalable backend applications with Node.js",
    thumbnail: "/nodejs-course-thumbnail.jpg",
    instructorId: "3",
    instructor: mockUsers.find((u) => u.id === "3"),
    status: "published" as const,
    price: 129,
    duration: 35,
    category: "Web Development",
    subcategory: "Backend",
    subject: "Node.js",
    language: "English",
    level: "Advanced",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "course3",
    title: "Python Data Science Fundamentals",
    description: "Learn data analysis and visualization with Python",
    thumbnail: "/python-data-science-course.png",
    instructorId: "6",
    instructor: mockUsers.find((u) => u.id === "6"),
    status: "draft" as const,
    price: 149,
    duration: 50,
    category: "Data Science",
    subcategory: "Analytics",
    subject: "Python",
    language: "English",
    level: "Beginner",
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-08"),
  },
]

export const mockTestSeries = [
  {
    id: "test1",
    title: "JavaScript Fundamentals Assessment",
    description: "Comprehensive test covering JS basics, functions, and DOM manipulation",
    courseId: "course1",
    duration: 60,
    totalMarks: 100,
    status: "published" as const,
    attempts: 156,
    questions: [
      {
        id: "q1",
        testSeriesId: "test1",
        question: "What is the correct way to declare a variable in JavaScript?",
        options: ["var x = 5;", "variable x = 5;", "v x = 5;", "declare x = 5;"],
        correctAnswer: 0,
        explanation: "The 'var' keyword is used to declare variables in JavaScript.",
        marks: 2,
        order: 1,
      },
      {
        id: "q2",
        testSeriesId: "test1",
        question: "Which method is used to add an element to the end of an array?",
        options: ["push()", "pop()", "shift()", "unshift()"],
        correctAnswer: 0,
        explanation: "The push() method adds one or more elements to the end of an array.",
        marks: 2,
        order: 2,
      },
      {
        id: "q3",
        testSeriesId: "test1",
        question: "What does DOM stand for?",
        options: [
          "Document Object Model",
          "Data Object Management",
          "Dynamic Object Method",
          "Document Oriented Model",
        ],
        correctAnswer: 0,
        explanation: "DOM stands for Document Object Model, which represents the structure of HTML documents.",
        marks: 1,
        order: 3,
      },
    ],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "test2",
    title: "React Advanced Concepts",
    description: "Test series on hooks, context, performance optimization",
    courseId: "course1",
    duration: 90,
    totalMarks: 150,
    status: "draft" as const,
    attempts: 0,
    questions: [
      {
        id: "q4",
        testSeriesId: "test2",
        question: "What is the purpose of useEffect hook?",
        options: [
          "To manage component state",
          "To handle side effects in functional components",
          "To create custom hooks",
          "To optimize performance",
        ],
        correctAnswer: 1,
        explanation: "useEffect is used to handle side effects like API calls, subscriptions, etc.",
        marks: 3,
        order: 1,
      },
    ],
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
]

export const mockFreeVideos = [
  {
    id: "video1",
    title: "Introduction to JavaScript",
    description: "Learn the basics of JavaScript programming language",
    videoUrl: "/videos/js-intro.mp4",
    thumbnail: "/javascript-tutorial.png",
    duration: 25,
    views: 1250,
    status: "published" as const,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "video2",
    title: "CSS Grid Layout Tutorial",
    description: "Master CSS Grid for modern web layouts",
    videoUrl: "/videos/css-grid.mp4",
    thumbnail: "/css-grid-tutorial.jpg",
    duration: 18,
    views: 890,
    status: "published" as const,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "video3",
    title: "React Hooks Explained",
    description: "Understanding useState, useEffect, and custom hooks",
    videoUrl: "/videos/react-hooks.mp4",
    thumbnail: "/react-hooks-tutorial.png",
    duration: 32,
    views: 0,
    status: "draft" as const,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
]
